apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
  finalizers:
    - resources-finalizer.argocd.argoproj.io        
spec:
  project: default

  source:
    repoURL: https://github.com/codefresh-contrib/gitops-cert-level-3-examples.git
    targetRevision: HEAD
    path: ./application-ordering/manifests/db
   
  destination:
    server: https://kubernetes.default.svc
    namespace: my-db

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true
      selfHeal: true 
  
